config/routes.rb
RailsPortfolioApp::Application.routes.draw do
  root :to => 'pages#home'
  get 'about' => 'pages#about', :as => 'about'
  
  get 'class_projects' => 'class_projects#index', :as => 'projects_index'
  get 'class_project/:id' => 'class_projects#show', :as => 'project_show'
  
  get 'new_project' => 'class_projects#new', :as => 'new_project'
  post 'class_projects' => 'class_projects#create', :as => 'create_project'
  
  get 'class_project/:id/edit' => 'class_projects#edit', :as => 'edit_project'
  put 'class_project/:id' => 'class_projects#update', :as => 'update_project'
  
  get 'contacts' => 'contacts#index', :as => 'contacts_index'
  get 'contact/:id' => 'contacts#show', :as => 'contacts_show'
  
  get 'new_contact' => 'contacts#new', :as => 'new_contact'
  post 'contacts' => 'contacts#create', :as => 'create_contact'
  
  get 'contact/:id/edit' => 'contacts#edit', :as => 'edit_contact'
  put 'contact/:id' => 'contacts#update', :as => 'update_contact'
  
  get 'links' => 'links#index', :as => 'links_index'
  get 'link/:id' => 'links#show', :as => 'link_show'
  
  get 'new_link' => 'links#new', :as => 'new_link'
  post 'links' => 'links#create', :as => 'create_link'
  
  get 'link/:id/edit' => 'links#edit', :as => 'edit_link'
  put 'link/:id' => 'links#update', :as => 'update_link'
  
  get 'articles' => 'articles#index', :as => 'articles_index'
  get 'article/:id' => 'articles#show', :as => 'article_show'
  
  get 'new_article' => 'articles#new', :as => 'new_article'
  post 'articles' => 'articles#create', :as => 'create_article'
  
  get 'article/:id/edit' => 'articles#edit', :as => 'edit_article'
  put 'article/:id' => 'articles#update', :as => 'update_article'
  
  get 'liked/:id' => 'likes#new', :as => 'like_article'
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "create_login"
  
  post "create_user" => 'users#create', :as => "create_user"
  get "signup" => 'users#new', :as => "signup"

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :draft, :title
  validates :body, :title, presence: true
  has_many :likes
  
  def excerpt(body)
    excerptarray = body.split("")
    excerptarray[0...29].join("")
  end
  
  def relative_length
  end
  
end

app/models/class_project.rb
class ClassProject < ActiveRecord::Base
  attr_accessible :description, :github, :name, :other_url, :summary
  validates :name, :description, :github, :summary, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :message, :phone, :website
  validates :email, :first_name, :last_name, :message, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
   attr_accessible :ip_address, :liked, :article_id
   validates :article_id, uniqueness: true
   validates :article_id, :ip_address, presence: true
   belongs_to :article
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :name, :url
  validates :url, uniqueness: true
  validates :name, :url, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :type
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  has_secure_password
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end
  
  def show
    @contact = Contact.find(params[:id])
  end
  
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(params[:contact])
    
    if @contact.save
      redirect_to contacts_index_path
    else
      render 'new'
    end
  end
  
  def edit
    @contact = Contact.find(params[:id])
  end
  
  def update
    @contact = Contact.find(params[:id])
    
    if @contact.update_attributes(params[:contact])
      redirect_to contacts_index_path
    else
      render 'edit'
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @article = Article.find(params[:id])
    @article.likes.create({:ip_address => request.remote_ip})
    
    if session[:liked_article_ids]
      session[:liked_article_ids] << @article.id
    else
      session[:liked_article_ids] = [@article.id]
    end
    
    redirect_to article_show_path(@article.id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end
  
  def show
    @link = Link.find(params[:id])
  end
  
  def new
    @link = Link.new
  end
  
  def create
    @link = Link.new(params[:link])
    
    if @link.save
      redirect_to links_index_path
    else
      render 'new'
    end
  end
  
  def edit
    @link = Link.find(params[:id])
  end
  
  def update
    @link = Link.find(params[:id])
    
    if @link.update_attributes(params[:link])
      redirect_to links_index_path
    else
      render 'edit'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to articles_index_path
    else
      raise "User could not be saved."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/class_project_helper.rb
module ClassProjectHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<% @contact.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>

<%= form_for(@contact, :url => update_contact_path) do |f| %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	
	<%= f.label :email %>
	<%= f.text_field :email %>
	
	<%= f.label :message %>
	<%= f.text_field :message %>
	
	<%= f.label :phone %>
	<%= f.text_field :phone %>
	
	<%= f.label :website %>
	<%= f.text_field :website %>
	
	<%= f.submit %>
	
<% end %>

app/views/contacts/index.html.erb
<h1>Contacts Index</h1>

<% @contacts.each do |contact| %>
  <p><%= link_to(contact.first_name + " " + contact.last_name, contacts_show_path(contact.id)) %></p>
<% end %>

<%= link_to("New Contact", new_contact_path) %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<% @contact.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>

<%= form_for(@contact, :url => create_contact_path) do |f| %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	
	<%= f.label :email %>
	<%= f.text_field :email %>
	
	<%= f.label :message %>
	<%= f.text_field :message %>
	
	<%= f.label :phone %>
	<%= f.text_field :phone %>
	
	<%= f.label :website %>
	<%= f.text_field :website %>
	
	<%= f.submit %>
	
<% end %>

app/views/contacts/show.html.erb
<p><%= @contact.first_name %></p>
<p><%= @contact.last_name %></p>
<p><%= @contact.message %></p>
<p><%= @contact.phone %></p>
<p><%= @contact.website %></p>